steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - "-f"
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: bash
    args: [
      '-c',
      'gcloud run deploy "$_SERVICE_NAME"
      --platform=managed
      --image="$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      --labels="managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID"
      --region="$_DEPLOY_REGION"
      --set-env-vars DATABASE_URL=$$DATABASE_URL
      --quiet
      --allow-unauthenticated
      '
    ]

    id: Deploy
    secretEnv: [
      'DATABASE_URL',
    ]
  - name: "gcr.io/google-appengine/exec-wrapper"
    entrypoint: "bash"
    args: [
      "-c",
      "/buildstep/execute.sh
      -i $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      -e DATABASE_URL=$$DATABASE_URL
      -s $_CLOUDSQL_INSTANCE_FULL_NAME
      -- npx prisma migrate deploy"
    ]
      # - "-c"
      # - "/buildstep/execute.sh -i Prismaが使えるコンテナイメージ -e DATABASE_URL=$$DATABASE_URL -s $_CLOUDSQL_INSTANCE_FULL_NAME -- yarn prisma migrate deploy"
    secretEnv: ["DATABASE_URL"]
    dir: "google-cloud-prisma-migrate"
    id: "apply-migrations"
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
# serviceAccount: "projects/${PROJECT_ID}/serviceAccounts/1022174569886-compute@developer.gserviceaccount.com"
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/database-url/versions/latest
      env: DATABASE_URL
substitutions:
  _SERVICE_NAME: pulumi-cloud-run
  _DEPLOY_REGION: asia-northeast1
  _AR_HOSTNAME: asia-northeast1-docker.pkg.dev
  _PLATFORM: managed
  _TRIGGER_ID: d597c42d-7d13-4ca7-a0ee-4b0adb0e3511
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - pulumi-cloud-run
